version: '3.7'

services:
  frontend:
    build: ./frontend
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`ceq.bizzudigital.com.br`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=letsencrypt"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
    depends_on:
      - backend
    networks:
      - web
      - whaticket

  backend:
    build: ./backend
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`api.ceq.bizzudigital.com.br`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls.certresolver=letsencrypt"
      - "traefik.http.services.backend.loadbalancer.server.port=5000"
    environment:
      - DB_HOST=mysql
      - DB_USER=whaticket
      - DB_PASS=whaticketpass
      - DB_NAME=whaticket
      - JWT_SECRET=supertokensecreto
      - CHROMELESS=true
    depends_on:
      - mysql
    networks:
      - web
      - whaticket

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=whaticket
      - MYSQL_USER=whaticket
      - MYSQL_PASSWORD=whaticketpass
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - whaticket

volumes:
  mysql_data:

networks:
  web:
    external: true
  whaticket:
    driver: bridge
